### ISSUE TITLE
Need Brief description on testing server

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#130]
Need brief description how to use testing server

**Comment by kolmanv** [comment]
Will update tomorrow.

**Comment by kolmanv** [comment]
In order to run testing server you will need to enable ssh without password from testing servers.
Meaning you just type ssh username@test.server.one from test.server.two and no password is needed.
In order to do that follow [those instructions](http://www.linuxproblem.org/art_9.html)
You can always add password to the configuration file and ignore the step above.

To run testing server, please run Master and Backup as described in [1.0.0 release notes](https://docs.google.com/document/d/1qFMYTv-iZFA1sZOBLxBjCbSPIHwtCuITl_8u_QW936I/edit).

Testing server will run remotely file_utils and validation gems, that is why you have to install them on testing.server.one (Assuming master is there). Testing server runs on the same machine as Backup server (testing.server.two).

file_utils is used to automatically generate files in Master server (testing.server.one):
file_utils --command=generate_files --conf_file=~/.bbfs/etc/file_generator.yml
Example of [file generation configuration file](https://github.com/bbfsdev/bbfs/blob/master/examples/file_generator.yml)

validation is used by testing server to validate content data is valid, both local (same machine as Backup on testing.server.two) and remote (Master on testing.server.one)

Running Testing server:
ruby -Ilib bin/testing_server --conf_file=~/.bbfs/etc/testing_server.yml
You can run it in background (add --bg_command=start) or in tmux (so that it will not die when you exit ssh).
Example of [testing server configuration file](https://github.com/bbfsdev/bbfs/blob/master/examples/testing_server.yml)

@AlexeyNemytov can you please go over those instructions and generate a wiki page? Do you have time for that?

**Comment by AlexeyNemytov** [comment]
ok:)

**Comment by AlexeyNemytov** [comment]
@kolmanv 
File utils not available
file_utils --command=generate_files --conf=/home/alexeyn/.bbfs/etc/file_generator.yml
-bash: file_utils: command not found

**Comment by kolmanv** [comment]
Did you try installing the gem?
gem install file_utils?
You can also build the gem from source and then build and install it locally
bbfs> gem build file_utils.gemspec
bbfs> gem install file_utils.0.0.9.......

**Comment by bbfsdev** [comment]
Obsolete - see comments in the binary:
https://github.com/bbfsdev/bbfs/blob/master/bin/testing_server
