### ISSUE TITLE
Testing Server Error

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#135]
ruby -Ilib bin/testing_server --conf_file=/home/alexeyn/.bbfs/etc/testing_server.yml

```
/home/alexeyn/bbfs/lib/params.rb:193:in `override_param': Parameter:'# Copy and change the configuration file before using. # To run this file use the following commandline' has not been defined and can not be overridden. It should first be defined through Param module methods:Params.string, Params.path, Params.integer, Params.float or Params.boolean. (RuntimeError)
        from /home/alexeyn/bbfs/lib/params.rb:299:in `block in read_yml_params'
        from /home/alexeyn/bbfs/lib/params.rb:298:in `each'
        from /home/alexeyn/bbfs/lib/params.rb:298:in `read_yml_params'
        from /home/alexeyn/bbfs/lib/params.rb:265:in `init'
        from bin/testing_server:11:in `<main>'
```

**Comment by AlexeyNemytov** [comment]
i modified testing_server.yml localy to match new params but it did not help

**Comment by kolmanv** [comment]
Alexey, please note, you have to add quotes before and after you add code:
With quotes:

```
`block in read_yml_params'
```

Without quotes
`block in read_yml_params'

Press to edit this comment to see the syntax.

**Comment by kolmanv** [comment]
The error says that some parameter is not defined and you are trying to use it.
testing_server:11 says: 
The error says: Parameter:'# Copy
And the code is: raise("Parameter:'#{name}' has not be
That means the you have problem with the YAML file, **please attach it**.
Seems like YAML things "# Copy..." is name of parameter... while it is a comment.

**Comment by AlexeyNemytov** [comment]
```
# Copy and change the configuration file before using.
# To run this file use the following commandline:
# testing_server --conf_file=examples/testing_server.yml [--bg_command=start]
content_server_hostname: 'f1.test.kbb1.com' # Remote host name of master (content) server.
content_server_files_port: 5444 # TCP/IP port to start server to send files to backup.
# TCP/IP port to start server to send content data upon request from client.
content_server_data_port: 5333 

# Path to config file in remote master (content) server.
content_file_generator_config: '/home/alexeyn/.bbfs/etc/file_generator.yml'
# Local path to copy master server index file to.
local_content_data_path: '/home/alexeyn/.bbfs/var/content.data'
# Local path to index (content data) file.
local_content_data_path: '/home/alexeyn/.bbfs/var/backup.data'

log_write_to_file: true # Will print all log messages to file
log_file_name: '~/.bbfs/log/backup_server.log4r'
log_write_to_console: true # Will print all log messages to standard output. Default is false.
log_write_to_email: true # Will print errors to mail on system crush only . Default is false.
# Verbosity of logging. 0 will log INFO messages. 3 will print ALL debug messages as well.
log_debug_level: 0 

from_email: 'bbfsdev@gmail.com' # From gmail address for update.
from_email_password: '*********' # From gmail password.
to_email: 'bbfsdev@gmail.com' # Destination email for updates.

remote_content_save_timeout: 120
```

_Added ``` ```_ around the configuration file.

**Comment by yarondbb** [comment]
Looks like the first 2 lines (until the ':' char) in the ymal file are excidently parsed as parameter name.. not sure why..
I had issues with yml file while copying text from one program to another. It seems that the # char is not recognized.
Try to copy the text first to some trusted editor (RubyMine?) then to the place were you run it. Or other copy..

**Comment by AlexeyNemytov** [comment]
Strange did it notepad++

**Comment by genadyp** [comment]
@AlexeyNemytov 
@yarondbb 
@kolmanv 
If you are prepare yml config file on windows and then using it on linux
i suggest to process it on linux with following command:

> sed -i -e 's/\r$//' fie_name.yml

it removes windows end-of-line, i already had a number of problems with it.

**Comment by bbfsdev** [comment]
@AlexeyNemytov @genadyp @yarondbb 
It's very hard to run testing server . . . We have to thing how to make it easier....

I have submitted a small fix to params.rb for testing server to work easier.
Note that after changing params.rb file I had to build the gem locally and install params v1.0.2!!!
Otherwise, testing_server will not work nether file_utils (to generate files) which depends on it.
Note that running from code will always take the latest version, so no need to unistall v1.0.1.

I'm checking testing server on f1 and f2. Using the following tmux session (you can join from your account):
tmux -S /tmp/kolman_pair attach

Syncing to master... on f1 and f2 in the bbfs directory:
git checkout master
git pull origin master
gem list # Check gems
rvm gemset list   # Setting the correct gemset ...
rvm gemset use dev
gem list # Check gems again
bundle install
gem list # Now all ready to launch...

Prepare Master (f1):
cp examples/config_content_server.yml ~/.bbfs/etc/
vi ~/.bbfs/etc/config_content_server.yml  # Edit the configuration file... fix paths if needed, fix ports, add email + password for email.
rm -rf ~/.bbfs/test_files/\* 
rm ~/.bbfs/var/content.data
ruby -Ilib bin/content_server

Prepare Backup (f2):
cp examples/config_backup_server.yml ~/.bbfs/etc/
vi ~/.bbfs/etc/config_backup_server.yml  # Edit the configuration file... fix paths if needed, fix ports, add email + 
rm -rf ~/.bbfs/backup_files/\* 
rm ~/.bbfs/var/backup.data
ruby -Ilib bin/backup_server

Simple check that backup works (run from f1):
echo 'aaa' > ~/.bbfs/test_files/aaa.txt

After several minutes! not less, check backup server:
[kolmanv@f2 bbfs]$ ls -l ~/.bbfs/backup_files/
total 12
drwxrwxr-x 3 kolmanv kolmanv 4096 May 29 05:02 97
drwxrwxr-x 3 kolmanv kolmanv 4096 May 29 04:59 remote
drwxrwxr-x 3 kolmanv kolmanv 4096 May 29 05:02 tmp
[kolmanv@f2 bbfs]$ 

All works, now we want to run Testing server.....
Please note that in order for testing server to work, you have to check you can ssh from f2 to f1 without password, i.e., ssh $USER@f1... will succeed without asking your password. How to do that written [here](http://www.linuxproblem.org/art_9.html).
@f1> cp examples/file_generator.yml ~/.bbfs/etc/file_generator.yml   # Prepare file generation configuration file on f1
@f1> gem build file_utils.gemspec
@f1> gem install file_utils-1.0.1.gem
@f2> cp examples/testing_server.yml ~/.bbfs/etc/  # Prepare testing server configuration on f2
@f2> vi ~/.bbfs/etc/testing_server.yml  # Edit testing server configuration file...
@f2> rvm gemset use dev  # Each time you open a new console you have to do that...
@f2> ruby -Ilib bin/testing_server # Run testing server

**Comment by bbfsdev** [comment]
Obsolete.
