### ISSUE TITLE
Backup server does not transfer files from content_server

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#138]
@kolmanv @yarondbb @genadyp 
1. Backup Server - status running OK - no errors
2. Content Server - status running OK - no errors
3. Files are created by file_generator
4. Yesterday 17.05 19:06 Jerusalem time was the last time file was transfered fro content to backup
Logs are attached
a. [backup.data](https://docs.google.com/file/d/0B9ar2vWqP86Va0dvb2tSMlhMdHM/edit?usp=sharing).
b. [backup_server.log4r](https://docs.google.com/file/d/0B9ar2vWqP86VYkwtTTVhOWszZ3c/edit?usp=sharing).

**Comment by bbfsdev** [comment]
Please attach configuration files and log of content server.
Then reassign back to me.

**Comment by AlexeyNemytov** [comment]
@kolmanv 
c.[content_server.log4r (rar)](https://docs.google.com/file/d/0B9ar2vWqP86VRGRtREdYMGl2ak0/edit?usp=sharing)
d.[config_backup_server.yml](https://docs.google.com/file/d/0B9ar2vWqP86VRDRxSjJNTW93UGc/edit?usp=sharing)
e. [config_content_server.yml](https://docs.google.com/file/d/0B9ar2vWqP86VcHdDWUhrN203WE0/edit?usp=sharing)

**Comment by yarondbb** [comment]
Looking on end of backup.data log:

   Backup sends ping requests and get latest content server data.
   No files are requested.
There can be reasons for this:
   No difference is performed in backup server
   Difference finds no new contnets - this might be if random values of new files is small?

Few questions:
1. What about the testing server mechanizm? Does is shows a difference bwteen content_Server and backup server contents?
2. What are the random parameters you use in the testing server?

Suggestion:
1. For next runs of testing round clock pls put log in debug-level-2  since this is the code which checks the diff (see the debug2 msg)
all_threads << Thread.new do
      loop do
        sleep(Params['backup_check_delay'])
        local_cd = dynamic_content_data.last_content_data()
        remote_cd = content_server_dynamic_content_data.last_content_data()
        diff = ContentData::ContentData.remove(local_cd, remote_cd)
        Log.debug2("Files to send? #{!diff.empty?}")
        #file_copy_client.request_copy(diff) unless diff.empty?
        if !diff.empty?
          Log.info('Backup and remote contents need a sync:')
          Log.info("Backup content:\n#{local_cd}")
          Log.info("Remote content:\n#{remote_cd}")
          Log.info("Missing contents:\n#{diff}")
          Log.info('Requesting a copy')
          file_copy_client.request_copy(diff)
        end
      end
    end
2. We might want to log more data in the diff.. like showing the 2 contents in the log.

**Comment by AlexeyNemytov** [comment]
1. Run was done manually , not thru testing_server
2. What dou you mean by random parameters? File being created according to
   definitions in file_generator.yml

Before restarting the program again we have to find the problem, why files
are not being copied

**Comment by AlexeyNemytov** [comment]
@yarondbb @kolmanv @genadyp 
Yaron was right - same files where generated - thus not copied 
This issue is closed
testing continues - files being copied
