### ISSUE TITLE
Run in background enters in endless loop in certain scenarios

### ISSUE THREAD

**Issue by genadyp** [bbfsdev/bbfs#142]
Branch: Release 1.0.0

Run in background enters in endless loop when:
- issue incorrect background command
- delete command (but background process actually finished)
- start command for already running server (process still running after issue delete command)

**Comment by genadyp** [comment]
@kolmanv 
@yarondbb 
@AlexeyNemytov 

Volodia wants to check background option.
May be worth to define this issue as critical?

**Comment by yarondbb** [comment]
fixed in brnach: issue-142-background-loop
Root cause was endless while loop in bin<application> when execution finished with no exception and loop counter was not reduced below zero.
I cenceld the endless loop mechanism since we are not using it currently.
Pull request opend for @kolmanv. I will close this issue after merge

**Comment by yarondbb** [comment]
related to #220 (the pull request
